version: 0.2

phases:
  install:
    commands:
      - echo 'Installing Node js and yarn...'
      - curl -sL https://rpm.nodesource.com/setup_17.x | bash -
      - yum -y install nodejs npm --skip-broken
      - npm install --global yarn
    finally:
      - echo 'Node and Yarn Installed successfully ...' 
  pre_build:
    commands:
      - echo Installing Dependencies ...
      - yarn install
    finally:
      - echo Dependencies installed ...
  build:
    commands:
      - echo building file ...
      - yarn build
    finally:
      - echo Build successfully ...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory : public
